/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import TDA.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  [Terminado]
 */
public class RegistroMesa extends javax.swing.JFrame {

    private static ListaMesasElectoral listaGeneral = new ListaMesasElectoral();

    public static ListaMesasElectoral getListaGeneral() {
        return listaGeneral;
    }
      
    /**
     * Creates new form RegistroCandidato
     */
    
    public RegistroMesa() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void gestionRegistro() {
        String nombreMesa = this.txtNumeroMesa.getText();
        // Busca la mesa específica en la listaGeneral
        MesaElectoral mesaSeleccionada = listaGeneral.returnMesa(nombreMesa);
        if (mesaSeleccionada != null) {
            // Pasa la mesa seleccionada al constructor de RegistroMienbroMesa
            RegistroMienbroMesa registroMiembro = new RegistroMienbroMesa(mesaSeleccionada);
            registroMiembro.setVisible(true); // Muestra la ventana para añadir miembros a la mesa seleccionada
        } else {
            JOptionPane.showMessageDialog(this, "Mesa no encontrada.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroMesa = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGestionMienbro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbPresidente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbSecretario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbVocal = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnGestionActa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel1.setText("N° Mesa:");

        txtNumeroMesa.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        txtNumeroMesa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        txtNumeroMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroMesaActionPerformed(evt);
            }
        });

        btnRegistro.setBackground(new java.awt.Color(153, 255, 153));
        btnRegistro.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnRegistro.setText("Registrar");
        btnRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 0), null));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), null));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(153, 204, 255));
        btnModificar.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 32)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registro de Mesa Electoral");

        jLabel6.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel6.setText("Buscar N° Mesa:");

        txtBusca.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        txtBusca.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel2.setText("Miembro de Mesa:");

        btnGestionMienbro.setBackground(new java.awt.Color(153, 204, 255));
        btnGestionMienbro.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        btnGestionMienbro.setText("Gestión");
        btnGestionMienbro.setToolTipText("");
        btnGestionMienbro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));
        btnGestionMienbro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionMienbroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        jLabel3.setText("Presidente:");

        lbPresidente.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbPresidente.setText("Persona 1");

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        jLabel4.setText("Secretario:");

        lbSecretario.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbSecretario.setText("Persona 2");

        jLabel7.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        jLabel7.setText("Vocal:");

        lbVocal.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbVocal.setText("Persona 3");

        btnBuscar.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel8.setText("Acta Electoral:");

        btnGestionActa.setBackground(new java.awt.Color(153, 204, 255));
        btnGestionActa.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        btnGestionActa.setText("Gestión");
        btnGestionActa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));
        btnGestionActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionActaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnGestionActa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGestionMienbro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroMesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbPresidente)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSecretario)
                            .addComponent(lbVocal))
                        .addGap(38, 38, 38)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnGestionMienbro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnGestionActa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbPresidente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbSecretario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbVocal))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        this.txtNumeroMesa.setText("");
        this.txtBusca.setText("");
        lbPresidente.setText("");
        lbSecretario.setText("");
        lbVocal.setText("");
    }

    private void txtNumeroMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroMesaActionPerformed

    }//GEN-LAST:event_txtNumeroMesaActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed

        String numeroMesa = txtNumeroMesa.getText().trim();
        if (numeroMesa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de mesa.");
            return;
        }
        if (listaGeneral.buscarNumeraMesa(numeroMesa)) {
            JOptionPane.showMessageDialog(this, "Esta mesa electoral ya existe.");
        } else {
            MesaElectoral nuevaMesa = new MesaElectoral(numeroMesa);
            listaGeneral.AñadirFinal(nuevaMesa);
            JOptionPane.showMessageDialog(this, "Mesa electoral registrada exitosamente.");
            lbPresidente.setText("No asignado");
            lbSecretario.setText("No asignado");
            lbVocal.setText("No asignado");
            // Limpia los campos después del registro
            gestionRegistro();
        }
        
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String numeroBuscar = this.txtBusca.getText();
        String modificar = this.txtNumeroMesa.getText();

        if (modificar.trim().isEmpty()) {
            // Mostrar mensaje si el campo modificar está vacío
            JOptionPane.showMessageDialog(this, "El campo de número de mesa no puede estar vacío.");
        } else if (listaGeneral.buscarNumeraMesa(numeroBuscar)) {
            // Si la mesa existe y el campo no está vacío, proceder con la modificación
            listaGeneral.modificarMesaElectoral(numeroBuscar, modificar);
            JOptionPane.showMessageDialog(this, "La mesa electoral: " + numeroBuscar + " ahora es: " + modificar);
        } else {
            // Si no se encuentra la mesa
            JOptionPane.showMessageDialog(this, "La Mesa no Existe");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String numeroBuscar = this.txtBusca.getText();
        if (listaGeneral.buscarNumeraMesa(numeroBuscar)) {
            listaGeneral.elimanarMesaElectoral(numeroBuscar);
            JOptionPane.showMessageDialog(this, "La mesa electoral: " + numeroBuscar + "fue eliminada");
        } else {
            // Si no se encuentra, entonces modificar
            JOptionPane.showMessageDialog(this, "La Mesa no Existe");
        }
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnGestionMienbroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionMienbroActionPerformed

        String nombreMesa = this.txtNumeroMesa.getText();
        // Busca la mesa específica en la listaGeneral
        MesaElectoral mesaSeleccionada = listaGeneral.returnMesa(nombreMesa);
        if (mesaSeleccionada != null) {
            // Pasa la mesa seleccionada al constructor de RegistroMienbroMesa
            RegistroMienbroMesa registroMiembro = new RegistroMienbroMesa(mesaSeleccionada);
            registroMiembro.setVisible(true); // Muestra la ventana para añadir miembros a la mesa seleccionada
        } else {
            JOptionPane.showMessageDialog(this, "Mesa no encontrada.");
        }
    }//GEN-LAST:event_btnGestionMienbroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String nombreMesa = this.txtBusca.getText();
        MesaElectoral mesaBuscada = listaGeneral.returnMesa(nombreMesa);
        if (mesaBuscada != null) {
            PilaMienbrosMesa pilaMienbros = mesaBuscada.getPilaMiebros();
            // Verifica si la pila de miembros es null antes de intentar acceder a los miembros
            if (pilaMienbros != null) {
                MiembroMesa presidente = pilaMienbros.getMiembroPorTipo("Presidente");
                MiembroMesa secretario = pilaMienbros.getMiembroPorTipo("Secretario");
                MiembroMesa vocal = pilaMienbros.getMiembroPorTipo("Vocal");
                // Actualiza los labels según si se encontró o no un miembro
                this.lbPresidente.setText(presidente != null ? presidente.getNombre() + " " + presidente.getDni() : "No asignado");
                this.lbSecretario.setText(secretario != null ? secretario.getNombre() + " " + secretario.getDni() : "No asignado");
                this.lbVocal.setText(vocal != null ? vocal.getNombre() + " " + vocal.getDni() : "No asignado");
            } else {
                // Si la pila es null, muestra "No asignado" en los labels
                this.lbPresidente.setText("No asignado");
                this.lbSecretario.setText("No asignado");
                this.lbVocal.setText("No asignado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mesa no encontrada.");
            limpiar();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGestionActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionActaActionPerformed

        try {
            String nombreMesa = this.txtNumeroMesa.getText();
            // Busca la mesa específica en la listaGeneral       
            MesaElectoral mesaSeleccionada = listaGeneral.returnMesa(nombreMesa);
            
            RegistroActa registroActa = new RegistroActa(mesaSeleccionada);
            
            registroActa.setVisible(true); // Muestra la ventana para añadir miembros a la mesa seleccionada
        } catch (Exception e) {
            // Código para manejar la excepción
            JOptionPane.showMessageDialog(this, "Complete Los mienbros de esta mesa");

        }
    }//GEN-LAST:event_btnGestionActaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGestionActa;
    private javax.swing.JButton btnGestionMienbro;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPresidente;
    private javax.swing.JLabel lbSecretario;
    private javax.swing.JLabel lbVocal;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtNumeroMesa;
    // End of variables declaration//GEN-END:variables
}
