/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import javax.swing.*;

/**
 *
 * @author YANCE VALENZUELA Anthony 20224203[ultima Entrega] && Fabricio Eduardo Placido Chambi 20221977[ultima Entrega] 
 *    &&  David Eduardo Vilela Rivera 20222786[ultima Entrega]
 */
public class RegistroActa extends javax.swing.JFrame {

    private MesaElectoral mesaElectoral;


    /**
     * Creates new form RegistroCandidato
     */
    public RegistroActa() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public RegistroActa(MesaElectoral mesaElectoral) {
        this.mesaElectoral = mesaElectoral;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 
        ObtenerLabel();
    }
    //YANCE VALENZUELA Anthony 20224203-ObtenerLabel-[ultima Entrega] 
    public void ObtenerLabel() {
        MiembroMesa P = mesaElectoral.getPilaMiebros().getMiembroPorTipo("Presidente");
        MiembroMesa S = mesaElectoral.getPilaMiebros().getMiembroPorTipo("Secretario");
        MiembroMesa V = mesaElectoral.getPilaMiebros().getMiembroPorTipo("Vocal");
        lbNmesa.setText(mesaElectoral.getnMesa());
        lbPresidente.setText(P.getNombre() + " " + P.getTipoMienbro());
        lbSecretario.setText(S.getNombre() + " " + S.getTipoMienbro());
        lbVocal.setText(V.getNombre() + " " + V.getTipoMienbro());

        if (mesaElectoral.getActaElectoral() != null) {

            txtTitulo.setText(mesaElectoral.getActaElectoral().getTitulo());
            txtFecha.setText(mesaElectoral.getActaElectoral().getFecha());
            String VotantesRegist = String.valueOf(mesaElectoral.getActaElectoral().getVotantesRegistradosAc());
            txtvotantesRegistradosAc.setText(VotantesRegist);

            // Convertir los valores enteros a String y asignarlos a los campos de texto
            String VotoBlanco = String.valueOf(mesaElectoral.getActaElectoral().getVotoBlanco());
            String VotoNulo = String.valueOf(mesaElectoral.getActaElectoral().getVotoNulo());
            String VotoTotal = String.valueOf(mesaElectoral.getActaElectoral().getVotoTotal());
            String Obsv = mesaElectoral.getActaElectoral().getObs();

            // Configurar los textos de los campos de texto
            txtVotoBlanco.setText(VotoBlanco);
            txtVotoNulo.setText(VotoNulo);
            txtvotoTotal.setText(VotoTotal);
            txtObsv.setText(Obsv);
        } else {
            // Si no hay acta, los campos se quedan en blanco
            txtVotoBlanco.setText("");
            txtVotoNulo.setText("");
            txtvotoTotal.setText("");
            txtObsv.setText("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbNmesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPresidente = new javax.swing.JLabel();
        lbSecretario = new javax.swing.JLabel();
        lbVocal = new javax.swing.JLabel();
        btnRegistroActa = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtvotantesRegistradosAc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtCandidatoBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVotarCandidato = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtVotoCandidato = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbPartido = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtVotoBlanco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtObsv = new javax.swing.JTextField();
        txtVotoNulo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnSellarActa = new javax.swing.JButton();
        txtvotoTotal = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 236, 183));

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel1.setText("Titulo:");

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel2.setText("Fecha:");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jLabel5.setText("Registro de Acta Electoral");

        txtTitulo.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        txtFecha.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        txtFecha.setText("00/00/00");

        jLabel7.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel7.setText("N° Mesa:");

        lbNmesa.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        lbNmesa.setText("000000");

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel3.setText("1° Miembro:");

        jLabel8.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel8.setText("2° Miembro:");

        jLabel9.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel9.setText("3° Miembro:");

        lbPresidente.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        lbPresidente.setText("Persona 1");

        lbSecretario.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        lbSecretario.setText("Persona 2");

        lbVocal.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        lbVocal.setText("Persona 3");

        btnRegistroActa.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnRegistroActa.setText("Registrar Acta");
        btnRegistroActa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistroActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel18.setText("Votantes Registrados:");

        txtvotantesRegistradosAc.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel18))
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPresidente)
                            .addComponent(lbSecretario)
                            .addComponent(lbVocal)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvotantesRegistradosAc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbNmesa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnRegistroActa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbNmesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtvotantesRegistradosAc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbPresidente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSecretario)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVocal)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistroActa)
                .addGap(201, 201, 201))
        );

        jPanel2.setBackground(new java.awt.Color(255, 164, 43));

        txtCandidatoBuscar.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        txtCandidatoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCandidatoBuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel4.setText("Candidato:");

        btnVotarCandidato.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnVotarCandidato.setText("Votar");
        btnVotarCandidato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVotarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarCandidatoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel12.setText("Votos Candidato: ");

        txtVotoCandidato.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jLabel16.setText("Registrar los Votos de los Candidatos");

        jLabel17.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel17.setText("Partido:");

        lbPartido.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        lbPartido.setText("No Asigando");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCandidatoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVotoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbPartido))
                    .addComponent(btnVotarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCandidatoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(lbPartido))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVotoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnVotarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLabel6.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel6.setText("Votos Blanco:");

        jLabel11.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel11.setText("Votos Total:");

        txtVotoBlanco.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel13.setText("Observaciones:");

        jLabel10.setFont(new java.awt.Font("Sans Serif Collection", 1, 13)); // NOI18N
        jLabel10.setText("Votos Nulo:");

        txtObsv.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        txtVotoNulo.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jLabel14.setText("Registrar los Votos y Sellado");

        btnSellarActa.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnSellarActa.setText("Sellar");
        btnSellarActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellarActaActionPerformed(evt);
            }
        });

        txtvotoTotal.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(72, 72, 72))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtVotoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVotoNulo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvotoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtObsv, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnSellarActa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtVotoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVotoNulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvotoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObsv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(btnSellarActa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //David Eduardo Vilela Rivera 20222786-btnVotarCandidatoActionPerformed-[ultima Entrega] 
    private void btnVotarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarCandidatoActionPerformed

        if (mesaElectoral.getActaElectoral() == null) {
            JOptionPane.showMessageDialog(this, "Primero debe registrar el Acta Electoral para esta mesa.");
            return;
        }
        // Ahora puedes acceder a la cola de candidatos
        String candidato = txtCandidatoBuscar.getText().trim();

        if (candidato.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del candidato.");
            return;
        }
        // Buscar candidato
        Candidato candidatoEncontrado = mesaElectoral.getActaElectoral().getColaCandidatos().returnCandidato_Nombre(candidato);
               
        if (candidatoEncontrado != null) {
            // Proceso normal
            int votos = Integer.parseInt(txtVotoCandidato.getText().trim());

            lbPartido.setText(candidatoEncontrado.getPartidoPolitico());

            candidatoEncontrado.setVotos(votos);
                      
            JOptionPane.showMessageDialog(this, "Votos añadidos con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Candidato no encontrado.");
        }
    }//GEN-LAST:event_btnVotarCandidatoActionPerformed
    //Fabricio Eduardo Placido Chambi 20221977-btnRegistroActaActionPerformed-[ultima Entrega] 
    private void btnRegistroActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActaActionPerformed

        String titulo = txtTitulo.getText().trim();
        String fecha = RegistroEleciones.getEleccionesGenerales().getFecha();
        String nMesa = mesaElectoral.getnMesa().trim();
        String VotantesRegistrados = txtvotantesRegistradosAc.getText().trim();
        // Validación de campos
        if (titulo.isEmpty() || fecha.isEmpty() || VotantesRegistrados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los campos.");
            return;
        }
        int VotantesReg;

        try {
            VotantesReg = Integer.parseInt(VotantesRegistrados);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para votantes registrados.");
            return;
        }
        // Registro o actualización del acta electoral
        ActaElectoral acta = mesaElectoral.getActaElectoral();
        if (acta == null) {
            // Crear y asignar nueva acta
            acta = new ActaElectoral(titulo, nMesa, fecha, VotantesReg);

            acta.setColaCandidatos(RegistroCandidato.getColaGeneral().colaEncero()); // Asignar cola de candidatos en cero votos 

            mesaElectoral.setActaElectoral(acta);

            JOptionPane.showMessageDialog(this, "Acta Electoral registrada exitosamente.");
        } else {
            // Actualizar acta existente
            acta.setTitulo(titulo);
            acta.setFecha(fecha);
            acta.setnMesa(nMesa);
            acta.setVotantesRegistradosAc(VotantesReg);
            //acta.setColaCandidatos(RegistroCandidato.getColaGeneral()); // Reasignar cola de candidatos

            JOptionPane.showMessageDialog(this, "Acta Electoral ha sido modificada con éxito.");
        }
        // Verificar contenido de la cola
        System.out.println("--Verificando candidatos en el acta electoral--");
        acta.getColaCandidatos().printConsola();
    }//GEN-LAST:event_btnRegistroActaActionPerformed

    private void txtCandidatoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCandidatoBuscarActionPerformed

    }//GEN-LAST:event_txtCandidatoBuscarActionPerformed
//YANCE VALENZUELA Anthony 20224203-btnSellarActaActionPerformed-[ultima Entrega] 
    private void btnSellarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellarActaActionPerformed

        if (mesaElectoral.getActaElectoral() == null) {
            JOptionPane.showMessageDialog(this, "Primero realice el Registro de Acta Electoral.");
            return;
        }

        try {
            // Asignar datos del formulario al acta electoral
            int votoBlanco = Integer.parseInt(txtVotoBlanco.getText().trim());
            int votoNulo = Integer.parseInt(txtVotoNulo.getText().trim());
            int votoTotal = Integer.parseInt(txtvotoTotal.getText().trim());
            String obs = txtObsv.getText().trim();

            mesaElectoral.getActaElectoral().setVotoBlanco(votoBlanco);
            mesaElectoral.getActaElectoral().setVotoNulo(votoNulo);
            mesaElectoral.getActaElectoral().setVotoTotal(votoTotal);
            mesaElectoral.getActaElectoral().setObs(obs);

            JOptionPane.showMessageDialog(this, "Acta Electoral sellada exitosamente.");

            // Generar informe completo por Consola
            imprimirInformeMesa();

            // Mostrar reporte automáticamente en la ventana ReporteMesa
            ReporteMesa ventanaReporte = new ReporteMesa(mesaElectoral); // Llamar al constructor con la mesa
            ventanaReporte.setVisible(true); // Mostrar la ventana con el reporte

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores válidos para los campos de votos.");
        }

    }//GEN-LAST:event_btnSellarActaActionPerformed
//YANCE VALENZUELA Anthony 20224203-imprimirInformeMesa-[ultima Entrega] 
    private void imprimirInformeMesa() {
        System.out.println("----- INFORME GENERAL DE LA MESA ELECTORAL -----");
        System.out.println("Número de Mesa: " + mesaElectoral.getnMesa());
        System.out.println("Miembros de la Mesa:");
        mesaElectoral.getPilaMiebros().printConsola(); // Método para imprimir pila de miembros

        ActaElectoral acta = mesaElectoral.getActaElectoral();
        if (acta != null) {
            System.out.println("Acta Electoral:");
            System.out.println("Título: " + acta.getTitulo());
            System.out.println("Fecha: " + acta.getFecha());
            System.out.println("Número de Mesa: " + acta.getnMesa());
            System.out.println("Votantes Registrados: " + acta.getVotantesRegistradosAc());
            System.out.println("Votos Blancos: " + acta.getVotoBlanco());
            System.out.println("Votos Nulos: " + acta.getVotoNulo());
            System.out.println("Votos Totales: " + acta.getVotoTotal());
            System.out.println("Observaciones: " + acta.getObs());
            System.out.println("Candidatos en la Cola:");
            acta.getColaCandidatos().printConsola(); // Usa el método existente para imprimir los candidatos
        } else {
            System.out.println("No se ha registrado un acta electoral.");
        }
        System.out.println("------------------------------------------------");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroActa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroActa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroActa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroActa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroActa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroActa;
    private javax.swing.JButton btnSellarActa;
    private javax.swing.JButton btnVotarCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbNmesa;
    private javax.swing.JLabel lbPartido;
    private javax.swing.JLabel lbPresidente;
    private javax.swing.JLabel lbSecretario;
    private javax.swing.JLabel lbVocal;
    private javax.swing.JTextField txtCandidatoBuscar;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtObsv;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVotoBlanco;
    private javax.swing.JTextField txtVotoCandidato;
    private javax.swing.JTextField txtVotoNulo;
    private javax.swing.JTextField txtvotantesRegistradosAc;
    private javax.swing.JTextField txtvotoTotal;
    // End of variables declaration//GEN-END:variables
}
