/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import TDA.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author [Terminado]
 * 
 */
public class RegistroCandidato extends javax.swing.JFrame {

    private static ColaCandidatos ColaGeneral = new ColaCandidatos();

    public static ColaCandidatos getColaGeneral() {
        return ColaGeneral;
    }

    /**
     * Creates new form RegistroCandidato
     */
    public RegistroCandidato() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void limpiar() {
        txtname.setText("");
        txtApellido.setText("");
        txtDNI.setText("");
        txtPartido.setText("");
    }

    public String printLista(ColaCandidatos colaInstaceada, NodoCandidatos ptr) {
        if (ptr == null) {
            return "null";
        } else {
            return ptr.getCandidato().getNombre() + " -> " + printLista(colaInstaceada, ptr.getNext());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPartido = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscarCandidato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        txtApellido.setToolTipText("");
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel3.setText("DNI:");

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel4.setText("Partido Político:");

        txtPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartidoActionPerformed(evt);
            }
        });

        btnRegistro.setBackground(new java.awt.Color(153, 255, 153));
        btnRegistro.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnRegistro.setText("Registrar");
        btnRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 102, 0), null));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), null));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(153, 204, 255));
        btnModificar.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 32)); // NOI18N
        jLabel5.setText("Registro de Candidatos");

        jLabel6.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel6.setText("Buscar DNI:");

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });

        btnBuscarCandidato.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        btnBuscarCandidato.setText("Buscar");
        btnBuscarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCandidatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPartido, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarCandidato)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnRegistro)
                    .addComponent(btnEliminar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartidoActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
// Obtener los datos del formulario
        String nombre = txtname.getText().trim();
        String apellido = txtApellido.getText().trim();
        String dni = txtDNI.getText().trim();
        String partido = txtPartido.getText().trim();

        // Verificar que todos los campos estén llenos
        if (nombre.isEmpty() || apellido.isEmpty() || dni.isEmpty() || partido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.");
            return; // Salir si algún campo está vacío
        }

        // Verificar que el DNI no esté repetido
        NodoCandidatos nodo = ColaGeneral.front;
        while (nodo != null) {
            if (nodo.getCandidato().getDni().equals(dni)) {
                JOptionPane.showMessageDialog(this, "El DNI ya está registrado.");
                return; // Salir si el DNI ya existe
            }
            nodo = nodo.getNext();  // Avanzar al siguiente nodo
        }

        // Crear un nuevo Candidato
        Candidato nuevoCandidato = new Candidato(nombre, apellido, dni, partido);

        // Insertar el candidato en la cola
        ColaGeneral.inserta(nuevoCandidato);
        limpiar();
        JOptionPane.showMessageDialog(this, "Candidato registrado exitosamente.");
        ColaGeneral.printConsola();


    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String dni = txtBusca.getText().trim();

        // Verificar si el campo de DNI está vacío
        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el DNI del candidato a modificar.");
            return;
        }

        // Verificar si el DNI tiene el formato correcto
        if (dni.length() != 8 || !dni.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener 8 dígitos numéricos.");
            return;
        }

        // Buscar el miembro en la pila
        Candidato miembroExistente = ColaGeneral.returnCandidato_DNI(dni);

        if (miembroExistente != null) {
            // Si se encuentra el miembro, permitimos la modificación de los datos
            String nuevoNombre = txtname.getText().trim();
            String nuevoApellido = txtApellido.getText().trim();
            String nuevoDNI = txtDNI.getText().trim();
            String nuevoPartido = txtPartido.getText().trim();

            // Verificar que los nuevos datos no estén vacíos
            if (nuevoNombre.isEmpty() || nuevoApellido.isEmpty() || nuevoDNI.isEmpty() || nuevoPartido.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
                return;
            }

            // Modificar los datos del miembro
            miembroExistente.setNombre(nuevoNombre);
            miembroExistente.setApellido(nuevoApellido);
            miembroExistente.setDni(nuevoDNI);
            miembroExistente.setPartidoPolitico(nuevoPartido);

            limpiar();
            JOptionPane.showMessageDialog(this, "Datos del candidato fueron modificados exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un candidato con el DNI ingresado.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String dni = txtBusca.getText(); // Obtener el DNI ingresado en el campo de texto

        // Verificar que se ha ingresado un DNI
        if (dni == null || dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un DNI válido.");
            return;
        }

        // Intentar eliminar el miembro con el DNI dado en la pila de miembros de MesaElectoral
        if (ColaGeneral.buscarDNI(dni)) {
            ColaGeneral.eliminarCandidatos(dni);
            JOptionPane.showMessageDialog(this, "Candidato eliminado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún Candidato con ese DNI.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCandidatoActionPerformed

        String dni = txtBusca.getText().trim();

        // Verificar si el campo de DNI está vacío
        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el DNI del candidato a buscar.");
            return;
        }

        // Verificar si el DNI tiene el formato correcto (8 dígitos numéricos)
        if (dni.length() != 8 || !dni.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener 8 dígitos numéricos.");
            return;
        }

        // Buscar el candidato en la cola
        NodoCandidatos nodo = ColaGeneral.front;
        boolean candidatoEncontrado = false;

        while (nodo != null) {
            Candidato candidato = nodo.getCandidato();
            if (candidato.getDni().equals(dni)) {
                // Mostrar los datos del candidato si se encuentra
                txtname.setText(candidato.getNombre());
                txtApellido.setText(candidato.getApellido());
                txtDNI.setText(candidato.getDni());
                txtPartido.setText(candidato.getPartidoPolitico());
                candidatoEncontrado = true;
                break; // Salir del ciclo cuando el candidato se encuentra
            }
            nodo = nodo.getNext(); // Avanzar al siguiente nodo
        }

        if (!candidatoEncontrado) {
            JOptionPane.showMessageDialog(this, "No se encontró un candidato con el DNI ingresado.");
        }

    }//GEN-LAST:event_btnBuscarCandidatoActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCandidato;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtPartido;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
